(ns bedes-sleuth.bedes-schema)

(def bedes-headers
  ["Wall Insulation Location",
   "Audit Cost",
   "Design Food Sales - Gross Floor Area",
   "Exterior Shading Type",
   "Design Electricity Use - Grid Purchase",
   "Design Coal - Anthracite Use",
   "Static Pressure Reset Control",
   "Annual Water Savings",
   "Library - Computer Density",
   "Evaporatively Cooled Condenser Minimum Temperature",
   "Weather Normalized Site Natural Gas Use",
   "Mailing Center/Post Office - Weekly Operating Hours",
   "Fuel Interruptibility",
   "Restaurant - Weekly Operating Hours",
   "Indoor Water Cost",
   "Footprint Shape",
   "Guiding Principle 4.7 Indoor Environment - Tobacco Smoke Control",
   "Hotel - Gym/fitness Center Floor Area",
   "Refrigerant Return Line Diameter",
   "Transportation Terminal/Station - Computer Density",
   "Other - Recreation - Worker Density",
   "Outside Air Reset Minimum Heating Supply Temperature",
   "Typical Exterior Shading Depth",
   "Annual Net Emissions",
   "Combustion Efficiency",
   "Non-Refrigerated Warehouse - Percent That Can Be Cooled",
   "Design Other - Entertainment/Public Assembly - Gross Floor Area",
   "Schedule End Month",
   "Police Station - Number of Computers",
   "Other - Mall - Computer Density",
   "Other - Education - Weekly Operating Hours",
   "Ignition Type",
   "PV Module Rated Power",
   "Space Occupant Capacity",
   "Supply Duct Percent Conditioned Space",
   "Medical Office - Percent That Can Be Cooled",
   "Water collected for Reuse",
   "Convenience Store without Gas Station - Number of Workers on Main Shift",
   "Minimum Fan Speed as a Fraction of Maximum - Heating",
   "Senior Care Community - Percent That Can Be Heated",
   "Conveyance Standby Time",
   "Lighting Control Type Manual",
   "Wood Cost",
   "Hotel- Number of guest meals served per year",
   "Fitness Center/Health Club/Gym - Worker Density",
   "Floors Above Grade",
   "Contact Name",
   "Enclosed Mall - Weekly Operating Hours",
   "Cooling Delivery Type",
   "Dishwasher Year of Manufacture",
   "Percent of Total Electricity Generated from Onsite Renewable Systems",
   "Water/Wastewater Site EUI - Adjusted to Current Year",
   "Indoor Arena - Ice Events",
   "Personal Services - Computer Density",
   "Worship Facility - Commercial Refrigeration Density",
   "Guiding Principle 1.4 Integrated -Occupant Feedback",
   "Property Use Detail Alerts",
   "Premises Street Address 1",
   "Premises Street Address 2",
   "Evaporatively Cooled Condenser",
   "Other - Stadium - Percent That Can Be Heated",
   "Premises Name",
   "Foundation Wall Below Grade Depth",
   "Glass Type",
   "Certification Version",
   "Date Property Last Modified",
   "Bar/Nightclub - Computer Density",
   "Casino - Number of Workers on Main Shift",
   "Vertical Abutments",
   "Other - Technology/Science - Gross Floor Area",
   "Specular Reflectors",
   "Repair Services - Number of Computers",
   "Design Distribution Center - Gross Floor Area",
   "Third Party Certification Date Achieved",
   "Design Other - Technology/Science - Gross Floor Area",
   "Mailing Center/Post Office - Number of Workers on Main Shift",
   "Casino - Computer Density",
   "Motor Location Relative to Air Stream",
   "Audit Date",
   "Aquarium - Number of Workers on Main Shift",
   "Medical Office - Weekly Operating Hours",
   "Owner City",
   "Quantity of Processed Laundry",
   "NYC Borough, Block and Lot",
   "Premises Occupancy Classification",
   "Other - Public Services - Gross Floor Area",
   "Guiding Principle 2.3 Energy - Onsite Renewable",
   "Residence Hall/Dormitory - Room Density",
   "Interior Shading Type",
   "Window Width",
   "Lifestyle Center - Number of Computers",
   "Performing Arts - Weekly Operating Hours",
   "National Median Source Energy Use",
   "Floor Framing Factor",
   "Cooling Efficiency Units",
   "Fuel Oil #4 Use",
   "Evaporatively Cooled Condenser Maximum Temperature",
   "Sequencing",
   "Hotel- Hours per day guests on-site",
   "Other - Entertainment/Public Assembly - Weekly Operating Hours",
   "Minimum Part Load Ratio",
   "Generation Capacity",
   "Water Fixture Fraction Hot Water",
   "Energy/Power Station - Gross Floor Area",
   "Design Water/Wastewater Source EUI",
   "Other - Computer Density",
   "Primary Service Hot Water Type",
   "Source Energy Use Intensity",
   "Multifamily Housing - Number of Bedrooms",
   "Shared Resource System",
   "Worship Facility - Cooking Facilities",
   "Guiding Principle 4.3 Indoor Environment - Automated Lighting Controls",
   "K-12 School - Number of Workers on Main Shift",
   "Design Medical Office - Gross Floor Area",
   "Indoor Water Use",
   "Movie Theater - Number of Workers on Main Shift",
   "Regional Average EUI",
   "Other - Education - Computer Density",
   "Dishwasher Quantity",
   "Design Electricity Use - Grid Purchase and Onsite Renewable Energy",
   "Energy/Power Station - Number of Workers on Main Shift",
   "Pre-school/Daycare - Weekly Operating Hours",
   "Motor Application",
   "Premises County",
   "Fire Station - Number of Computers",
   "Other - Lodging/Residential - Worker Density",
   "Hotel- Number of Rooms",
   "Longitude",
   "Office - Percent That Can Be Cooled",
   "Federal Property",
   "Manufacturing/Industrial Plant - Weekly Operating Hours",
   "Medical Office - Gross Floor Area",
   "Outside Lighting Type",
   "Stadium - Number of Walk-in Refrigeration/Freezer Units",
   "Guiding Principle 1.3 Integrated - Plan",
   "Medical Office - Surgery Center Size",
   "Diesel Cost",
   "Senior Care Community - Living Unit Density",
   "Complete Resource",
   "Contact Type",
   "Fuel Oil #1 Use",
   "Roof Insulation Material",
   "Other - Technology/Science - Number of Computers",
   "Hot Water Reset Control",
   "College/University - Worker Density",
   "Solar Thermal System Collector Loop Type",
   "Window Layout",
   "Other - Specialty Hospital - Number of Computers",
   "Latitude",
   "Marginal Cost Rate",
   "Other - Restaurant/Bar - Weekly Operating Hours",
   "Design Residence Hall/Dormitory - Gross Floor Area",
   "Fast Food Restaurant - Number of Workers on Main Shift",
   "Ice/Curling Rink - Number of Computers",
   "Weather Normalized Site Natural Gas Intensity",
   "Door Operation",
   "Fitness Center/Health Club/Gym - Computer Density",
   "Adult Education - Number of Workers on Main Shift",
   "Other Water Sources: Combined Indoor/Outdoor or Other Use",
   "Central Refrigeration System",
   "Design Convenience Store with Gas Station - Gross Floor Area",
   "Building Operator Type",
   "Bank Branch - Percent That Can Be Cooled",
   "Water Cost",
   "Pipe Location",
   "Pump Control Type",
   "Design Barracks - Gross Floor Area",
   "Day Start Hour",
   "Guiding Principle 5.5 Materials - Ozone Depleting Compounds",
   "Design Fuel Oil #1 Use",
   "Design Fitness Center/Health Club/Gym - Gross Floor Area",
   "Cost Effectiveness Screening Method",
   "Energy Cost",
   "Restaurant - Gross Floor Area",
   "Cooling Refrigerant",
   "Certification Value",
   "Financial Office - Percent That Can Be Heated",
   "Design Other - Stadium - Gross Floor Area",
   "Wholesale Club/Supercenter- Gross Floor Area",
   "Pool Volume",
   "Floor Area Type",
   "Hotel - Worker Density",
   "Roller Rink - Number of Workers on Main Shift",
   "Static Pressure",
   "Other Water Sources - Outdoor Cost",
   "Food Sales - Gross Floor Area",
   "Roof Framing Factor",
   "Part Load Ratio Below Which Hot Gas Bypass Operates",
   "Equipment Disposal and Salvage Costs",
   "Minimum Power Factor Without Penalty",
   "Wall Exterior Solar Absorptance",
   "Outpatient Rehabilitation/Physical Therapy - Gross Floor Area",
   "Worship Facility - Number of Computers",
   "Design Energy Cost Intensity",
   "Percent Better than National Median Water/Wastewater Site EUI",
   "District Chilled Water Cost",
   "Wholesale Club/Supercenter- Percent That Can Be Heated",
   "Multifamily Housing - Number of Laundry Hookups in All Units",
   "Scenario Qualifier",
   "Skylight Glazing",
   "Audit Team Member Certification Type",
   "Space Number of FTE Workers",
   "Convenience Store with Gas Station - Worker Density",
   "Courthouse - Computer Density",
   "National Median Site EUI",
   "Other - Entertainment/Public Assembly - Number of Workers on Main Shift",
   "Fuel Oil Cost",
   "Azimuth",
   "Auditor Qualification",
   "Swimming Pool - Approximate Pool Size",
   "Number of Buildings",
   "Wall Insulation Condition",
   "Third Party Certification Date Anticipated",
   "Fan Type",
   "Design Other - Specialty Hospital - Gross Floor Area",
   "Senior Care Community - Number of Residential Electronic Lift Systems",
   "Design Target Energy Cost",
   "SHW Efficiency",
   "Typical Wall R-Value",
   "Conveyance Peak Time",
   "Other - Stadium - Percent That Can Be Cooled",
   "District Hot Water",
   "Data Center - PDU Output Site Energy",
   "Space Name",
   "Premises Year Completed",
   "Weather Normalized Site Electricity Intensity",
   "End Use",
   "Compressor Staging",
   "Senior Care Community - Commercial Refrigeration Density",
   "Other - Recreation - Number of Computers",
   "Motor Pole Count",
   "Number of Luminaires",
   "Schedule Day",
   "Room Density",
   "Adult Education - Number of Computers",
   "Vocational School - Gross Floor Area",
   "Reference For Rate Structure",
   "Recirculation Flow Rate",
   "Indoor Water Intensity",
   "Floor Framing Material",
   "Distribution Center - Weekly Operating Hours",
   "Water Use Type",
   "Space Floors Above Grade",
   "Natural Gas Cost",
   "Design Convenience Store without Gas Station - Gross Floor Area",
   "Hotel - Type of Laundry Facility",
   "Manufacturing/Industrial Plant - Computer Density",
   "Measure Life",
   "Parasitic Fuel Consumption Rate",
   "Propane Cost",
   "Net Refrigeration Capacity",
   "Solar Hot Water Present",
   "Owner Name",
   "Capacity Unit",
   "Other - Public Services - Number of Workers on Main Shift",
   "Percent Better than National Median Source EUI",
   "Humidity Control Minimum",
   "Maximum Outside Air Flow Rate",
   "Pump Power Demand",
   "Deck Type",
   "Target Source Energy Use",
   "Other - Public Services - Weekly Operating Hours",
   "Distribution Center - Gross Floor Area",
   "Primary Cooling Type",
   "Financial Office - Weekly Operating Hours",
   "Senior Care Community - Electronic Lift Density",
   "Site Energy Use Intensity",
   "Site EUI - Adjusted to Current Year",
   "Repair Services - Weekly Operating Hours",
   "K-12 School - Months in Use",
   "Floor Insulation Condition",
   "Electricity",
   "Municipally Supplied Reclaimed Water - Outdoor Use",
   "Vocational School - Worker Density",
   "Other Water Sources - Indoor Use",
   "Guiding Principles - % Complete",
   "Wholesale Club/Supercenter- Number of Open or Closed Refrigeration/Freezer Units",
   "PV System Racking System Tilt Angle Min",
   "Off-Cycle Heat Loss Coefficient",
   "Fast Food Restaurant - Gross Floor Area",
   "LEED Certification Audit Exemption",
   "US Agency Designated Covered Facility ID",
   "Distribution Center - Percent That Can Be Cooled",
   "Pump Efficiency",
   "Distribution Center - Number of Walk-in Refrigeration/Freezer Units",
   "Floors Below Grade",
   "Transportation Terminal/Station - Gross Floor Area",
   "Design Fuel Oil #5 & 6 Use",
   "Other - Number of Computers",
   "Guiding Principle 3.1 Indoor Water - Option 1",
   "Guiding Principle 3.1 Indoor Water - Option 2",
   "Electricity Price Escalation Rate",
   "Retail Store - Number of Cash Registers",
   "Laboratory - Gross Floor Area",
   "Design Manufacturing/Industrial Plant - Gross Floor Area",
   "Dryer Secondary Energy Use Per Load",
   "Investment in Energy Projects, Cumulative",
   "Conveyance Peak Power",
   "Design Site Energy Use",
   "Suction Vapor Temperature",
   "Senior Care Community - Number of Residential Living Units",
   "Restaurant - Number of Workers on Main Shift",
   "Electrical Plug Load Intensity",
   "Bank Branch - Weekly Operating Hours",
   "Design Hotel - Gross Floor Area",
   "Alternative Water Generated On-Site - Outdoor Cost",
   "Air Distribution Configuration",
   "Electricity Use - Generated from Onsite Renewable Systems and Used Onsite",
   "Skylight Window Treatments",
   "Biomass GHG Emissions",
   "Race Track - Number of Workers on Main Shift",
   "Supermarket/Grocery - Number of Walk-in Refrigeration/Freezer Units",
   "Veterinary Office - Weekly Operating Hours",
   "Design Supermarket/Grocery Store - Gross Floor Area",
   "Design District Chilled Water Use",
   "Senior Care Community - Commercial Washing Machine Density",
   "Parking - Open Parking Lot Size",
   "Direct GHG Emissions",
   "Race Track - Number of Computers",
   "Chiller Compressor Type",
   "Fast Food Restaurant - Worker Density",
   "Veterinary Office - Computer Density",
   "Repair Services - Computer Density",
   "Other Water Sources - Indoor Cost",
   "Design Bar/Nightclub - Gross Floor Area",
   "Supply Air Temp Reset Control",
   "Cooling Equipment Maintenance Frequency",
   "Medical Office - Worker Density",
   "Bowling Alley - Weekly Operating Hours",
   "Boiler Insulation Thickness",
   "Supermarket/Grocery - Open or Closed Refrigeration Density",
   "Hospital - Number of MRI Machines",
   "Property Data Administrator - Email",
   "Coefficient of Performance",
   "Setup temperature cooling",
   "Other - Utility - Number of Computers",
   "Design Social/Meeting Hall - Gross Floor Area",
   "District Steam Use",
   "Design Source EUI",
   "Design Source EUI",
   "Design Fuel Oil #2 Use",
   "Measure End Date",
   "Other - Entertainment/Public Assembly - Number of Computers",
   "Office - Number of Computers",
   "Design Wholesale Club/Supercenter - Gross Floor Area",
   "Resource Units",
   "Typical Skylight Frame Type",
   "Stadium - Ice Events",
   "Diesel #2 Use",
   "Measure Description",
   "Roof Insulation Continuity",
   "Water Intensity",
   "Net Emissions",
   "Heat Pump Water Heater Refrigerant Designation",
   "AC Adjusted",
   "Medical Office - Number of Workers on Main Shift",
   "Skylight Pitch",
   "Natural Gas",
   "Supply Air Temperature Setpoint",
   "Publicly Subsidized",
   "Kerosene Use",
   "Wholesale Club/Supercenter- Weekly Operating Hours",
   "Burner Turndown Ratio",
   "Skylights Visible Transmittance",
   "Ice/Curling Rink - Number of Workers on Main Shift",
   "Design Zoo - Gross Floor Area",
   "Exterior Roughness",
   "Rate Structure Sector",
   "Chilled Water Supply Temperature",
   "Exterior Wall Color",
   "Emissions Factor",
   "Storage Tank Insulation Thickness",
   "Static Pressure - Installed",
   "Fixed Monthly Charge",
   "Lighting Efficacy",
   "Parking - Partially Enclosed Parking Garage Size",
   "Senior Care Community - Average Number of Residents",
   "Exterior Wall Type",
   "Guiding Principle 1.2 Integrated - Goals",
   "Premises Notes",
   "Drinking Water Treatment & Distribution - Average Flow",
   "Prison/Incarceration - Weekly Operating Hours",
   "Other - Recreation - Weekly Operating Hours",
   "SHW Year installed",
   "Measure Notes",
   "SHW is FEMP Designated Product",
   "Data Center - UPS System Redundancy",
   "Lamp Subtype",
   "Owner State",
   "Number of Lamps per Ballast",
   "Portfolio Manager Property ID",
   "Makeup Air Source",
   "PVc System Racking System Tilt Angle Max",
   "Fuel Oil #5 & 6 Use",
   "Other - Services - Computer Density",
   "Vertical Fin Depth",
   "Transformer Nameplate Efficiency",
   "US Federal Real Property Unique Identifier",
   "Guiding Principle 4.4 Daylighting and Occupant Controls - Option 2",
   "Guiding Principle 4.4 Daylighting and Occupant Controls - Option 1",
   "Net Metering",
   "Indoor Arena - Percent That Can Be Cooled",
   "Lighting Control Type Daylighting",
   "Solar Thermal System Collector Type",
   "Library - Gross Floor Area",
   "County",
   "Process Load Heat Gain Fraction",
   "Target Site EUI",
   "Weather Normalized Site Energy Use",
   "Motor Efficiency",
   "Multifamily Housing - Number of Laundry Hookups in Common Area",
   "Source Energy Use",
   "Site Energy Use",
   "Stadium - Number of Sporting Events per Year",
   "Repair Services - Worker Density",
   "NYC Building Identification Number",
   "Installation Type",
   "Courthouse - Number of Workers on Main Shift",
   "Other - Technology/Science - Number of Workers on Main Shift",
   "Library - Worker Density",
   "Site Energy Use",
   "Cell Count",
   "Aquarium - Weekly Operating Hours",
   "Other - Mall - Number of Workers on Main Shift",
   "Heating Equipment Maintenance Frequency",
   "Condenser Water Temperature",
   "Refrigerated Warehouse - Worker Density",
   "Residence Hall/Dormitory - Percent That Can Be Cooled",
   "Heat Pump Backup system fuel",
   "Motor Drive Efficiency",
   "Cooling Efficiency Value",
   "Electricity Use - Grid Purchase",
   "Auditor Qualification Number",
   "Coal Cost",
   "PM Administrator",
   "Recover Efficiency",
   "Outdoor Water Use",
   "Terrace R-Value",
   "Typical Skylight Frames R-Value",
   "Off-Peak Occupancy Percentage",
   "Operable Windows",
   "Site Energy Use - Adjusted to Current Year",
   "Motor Brake HP",
   "Federal Agency/Department",
   "Hospital - Staffed Bed Density",
   "Design Enclosed Mall - Gross Floor Area",
   "Software program version",
   "Economizer Dry Bulb Control Point",
   "Design Non-Refrigerated Warehouse - Gross Floor Area",
   "Parking - Supplemental Heating",
   "Skylight Type",
   "Rated Heat Pump Sensible Heat Ratio",
   "Daily Water Use",
   "Financial Office - Worker Density",
   "Premises State",
   "Alternative Water Generated On-Site: Combined Indoor/Outdoor or Other Use",
   "Social/Meeting Hall - Worker Density",
   "Draft Type",
   "Minimum Dimming Light Fraction",
   "Cooled Floor Area",
   "Stadium - Number of Concert/Show Events per Year",
   "Ventilation Rate",
   "Refrigerated Case Doors",
   "Guiding Principles - % Not Applicable",
   "Name of Retro-commissioning Certification Holder",
   "Metal Halide Start Type",
   "Measure First Cost",
   "Library - Weekly Operating Hours",
   "Perimeter",
   "Condenser Type",
   "Adult Education - Worker Density",
   "Luminaire Height",
   "Supermarket/Grocery - Cash Register Density",
   "Design K-12 School - Gross Floor Area",
   "Percent Better than National Median Site EUI",
   "Financial Office - Gross Floor Area",
   "Zoo - Worker Density",
   "Direct GHG Emissions Intensity",
   "Water Use",
   "Dehumidification Type",
   "Prison/Incarceration - Worker Density",
   "Guiding Principle 2.2 Energy - Efficient Products",
   "Output Capacity",
   "Cooking Equipment is Third Party Certified",
   "Guiding Principles - % Not Assessed",
   "Urgent Care/Clinic/Other Outpatient - Worker Density",
   "Day End Hour",
   "Guiding Principle 2.1 Energy - Energy Efficiency Any Option",
   "Alternative Water Generated On-Site - Indoor Use",
   "Utility Account Number",
   "Skylight to Roof Ratio",
   "Weather Normalized Water/Wastewater Site Electricity Intensity",
   "Weather Year",
   "Convention Center - Computer Density",
   "Winter Peak Electricity Reduction",
   "Target Source EUI",
   "Number of Meals",
   "Indirect GHG Emissions Intensity",
   "Design Ambulatory Surgical Center - Gross Floor Area",
   "Non-Refrigerated Warehouse - Number of Worker on Main Shift",
   "Humidification Type",
   "Casino - Number of Computers",
   "Weather Normalized Site Electricity",
   "Design Natural Gas Use",
   "Design Restaurant - Gross Floor Area",
   "Water/Wastewater Source EUI - Adjusted to Current Year",
   "Design Energy/Power Station - Gross Floor Area",
   "Design Indirect GHG Emissions",
   "Stadium - Computer Density",
   "Other - Stadium - Number of Computers",
   "Dishwasher Energy Factor",
   "Coal - Anthracite Use",
   "Other - Education - Number of Computers",
   "Supply Fraction of Duct Leakage",
   "Worship Facility - Computer Density",
   "Weather Station Category",
   "Foundation Wall Insulation Thickness",
   "Space Number Main Shift Workers",
   "Data Center - IT Equipment Input Site Energy",
   "On-site Renewable Electricity",
   "Date of Last PM Modification",
   "Municipally Supplied Potable Water: Combined Indoor/Outdoor or Other Cost",
   "Slab Insulation Condition",
   "Police Station - Number of Workers on Main Shift",
   "Number of Discrete Fan Speeds - Heating",
   "Number of Ballasts per Luminaire",
   "Outside Air Temperature Upper Limit Cooling Reset Control",
   "Fluorescent Start Type",
   "Chilled Water Reset Control",
   "Anti-Sweat Heater Power",
   "Federal Region/Sub-Department",
   "Outpatient Rehabilitation/Physical Therapy - Number of Computers",
   "Other - Lodging/Residential - Computer Density",
   "Design District Hot Water Use",
   "Boiler Type",
   "Bar/Nightclub - Weekly Operating Hours",
   "Senior Care Community - Gross Floor Area",
   "Point Of Use",
   "Summer Peak Electricity Reduction",
   "Slab Perimeter",
   "Lighting Control Type Timer",
   "Other HVAC Type",
   "Guiding Principle 4.1 Indoor Environment - Ventilation and Thermal Comfort",
   "Demand Reduction",
   "Green Power - Offsite",
   "Other - Recreation - Gross Floor Area",
   "Percent of Window Area Shaded",
   "Food Service - Gross Floor Area",
   "Mailing Center/Post Office - Worker Density",
   "Automobile Dealership - Worker Density",
   "Water/Wastewater Site EUI",
   "Design Drinking Water Treatment & Distribution - Gross Floor Area",
   "Steam Boiler Maximum Operating Pressure",
   "Investment in Energy Projects, Cumulative",
   "Other - Stadium - Number of Special/Other Events per Year",
   "Municipally Supplied Potable Water - Indoor Use",
   "Tank Volume",
   "Worship Facility - Gross Floor Area",
   "Design Other - Education - Gross Floor Area",
   "Municipally Supplied Reclaimed Water - Indoor Cost Intensity",
   "Utility Meter Number",
   "Target Total GHG Emissions Intensity",
   "Setpoint temperature cooling",
   "Ice/Curling Rink - Computer Density",
   "Fan Power Minimum Ratio",
   "Other - Stadium - Ice Events",
   "Weather Type",
   "PM Profile Status",
   "Other - Lodging/Residential - Gross Floor Area",
   "Annual Combined Whole Building Annual Weather Normalized Site Resource Use",
   "Design Diesel #2 Use",
   "Target Water/Wastewater Site EUI",
   "Stadium - Number of Computers",
   "Motor HP",
   "Convenience Store without Gas Station - Number of Computers",
   "Police Station - Worker Density",
   "Chiller Compressor Driver",
   "Multifamily Housing - Resident Population Type",
   "Strip Mall - Number of Workers on Main Shift",
   "Ventilation Type",
   "Courthouse - Percent That Can Be Heated",
   "Refrigerated Warehouse - Weekly Operating Hours",
   "Supply Air Control Strategy",
   "Software program used",
   "Duct Type",
   "Cooling Supply Air Temperature",
   "Personal Services - Gross Floor Area",
   "Duct Leakage Test Method",
   "Ventilation Zone Control",
   "Funding from Tax Credits",
   "Vocational School - Weekly Operating Hours",
   "Absorption Heat Source",
   "Transportation Terminal/Station - Worker Density",
   "Repair Services - Gross Floor Area",
   "Slab Insulation Orientation",
   "Alternative Water Generated On-Site - Outdoor Use",
   "Adult Education - Weekly Operating Hours",
   "Target ENERGY STAR Score",
   "Design Vocational School - Gross Floor Area",
   "Municipally Supplied Potable Water: Combined Indoor/Outdoor or Other Use",
   "Outside Air Reset Minimum Cooling Supply Temperature",
   "Normalization Years",
   "Tank Heating Type",
   "Electricity Use - Generated from Onsite Renewable Systems and Exported",
   "Other - Number of Workers on Main Shift",
   "Average Daily Hours",
   "Courthouse - Number of Computers",
   "eGRID Output Emissions Rate",
   "Other - Stadium - Enclosed Floor Area",
   "Stadium - Number of Concert/Show Events per Year",
   "Design Financial Office - Gross Floor Area",
   "Target Finder EUI",
   "ENERGY STAR Certification - YearCertified",
   "Coke Use",
   "Adult Education - Gross Floor Area",
   "NAICS Code",
   "Self-Storage Facility - Number of Workers on Main Shift",
   "ENERGY Star Score",
   "Process Load Duty Cycle",
   "Floor-to-Ceiling Height",
   "Single Family Home - Density of People",
   "Alternative Water Generated On-Site: Combined Indoor/Outdoor or Other Cost",
   "Other - Mall - Worker Density",
   "Number of Discrete Fan Speeds - Cooling",
   "Vocational School - Computer Density",
   "Other - Recreation - Computer Density",
   "Museum - Computer Density",
   "Convenience Store without Gas Station - Worker Density",
   "Zoo - Weekly Operating Hours",
   "Receive Date",
   "Weather Station ID",
   "Design Automobile Dealership - Gross Floor Area",
   "Fenestration Area",
   "Aquarium - Gross Floor Area",
   "NPV of Tax Implications",
   "Casino - Worker Density",
   "Window to Wall Ratio",
   "Internal Rate of Return",
   "Residence Hall/ Dormitory - Computer Lab",
   "Defrost Type",
   "Supermarket/Grocery - Percent That Can Be Heated",
   "Design Greenhouse Gas Emissions",
   "Energy Cost Intensity",
   "Guiding Principle 2.4 Energy - Measurement and Verification",
   "Ambulatory Surgical Center - Worker Density",
   "Building Certification",
   "Door Visible Transmittance",
   "Convenience Store without Gas Station - Gross Floor Area",
   "Weather Data Station ID",
   "Plug Load Peak Power",
   "Type of Measure",
   "Active Dehumidification",
   "Design ENERGY STAR Score",
   "Wholesale Club/Supercenter- Exterior Entrance to the Public",
   "College/University - Weekly Operating Hours",
   "Kerosene Cost",
   "Design Target Source Energy Use",
   "Design Liquid Propane Use",
   "Window Orientation",
   "Fitness Center/Health Club/Gym - Number of Workers on Main Shift",
   "National Median Energy Cost",
   "Dryer Primary Energy Use Per Load",
   "Library - Number of Computers",
   "Alternative Water Generated On-Site - Indoor Intensity",
   "Fan Design Static Pressure",
   "Electricity Use - Grid Purchase",
   "Office - Gross Floor Area",
   "Measure Start Date",
   "Demand Window",
   "Recirculation Loop Count",
   "Lot Size",
   "K-12 School - Refrigeration Density",
   "Compressor Unloader",
   "Design Multifamily Housing - Gross Floor Area",
   "Annual Fuel Use Native Units",
   "Municipally Supplied Potable Water - Indoor Cost Intensity",
   "Convenience Store with Gas Station - Computer Density",
   "Clothes Washer Modified Energy Factor",
   "Multifamily Housing - Gross Floor Area",
   "Worship Facility - Number of Commercial Refrigeration/Freezer Units",
   "Number of Refrigerant Return Lines",
   "National Median Source EUI",
   "Property Data Administrator",
   "Natural Ventilation Method",
   "Type of Rate Structure",
   "Outpatient Rehabilitation/Physical Therapy - Computer Density",
   "K-12 School - Student Seating Density",
   "Performing Arts - Worker Density",
   "Percent of Roof Terraces",
   "Cooling Control Strategy",
   "Rate Structure Effective Date",
   "Overhang Height above Window",
   "Typical Skylights SHGC",
   "MV Cost",
   "Transportation Terminal/Station - Number of Computers",
   "Race Track - Worker Density",
   "Target % Better Than Median Source EUI",
   "Guiding Principle 3.2 Water - Outdoor Water Any Option",
   "Other - Utility - Gross Floor Area",
   "Alternative Water Generated On-Site - Indoor Cost",
   "PV Module Width",
   "District Hot Water Use",
   "PM Sharing Account",
   "Hospital - Owned By",
   "Evaporative Cooling Entering Supply Air WB Temperature",
   "Roof Insulation Thickness",
   "National Median Water/Wastewater Source EUI",
   "Fitness Center/Health Club/Gym - Number of Computers",
   "Percent Savings in Lighting Power Density",
   "Performing Arts - Number of Workers on Main Shift",
   "Ambulatory Surgical Center - Computer Density",
   "Design Refrigerated Warehouse - Gross Floor Area",
   "Typical Window Frame R-Value",
   "Evaporative Cooling Operation",
   "Liquid Propane Cost",
   "Other - Specialty Hospital - Weekly Operating Hours",
   "Design Self-Storage Facility - Gross Floor Area",
   "Water/Wastewater Source EUI",
   "Senior Care Community - Worker Density",
   "Design Outpatient Rehabilitation/Physical Therapy - Gross Floor Area",
   "Wholesale Club/Supercenter- Number of Cash Registers",
   "Heating Type",
   "Annual Heating Efficiency Value",
   "Percentage of Common Space",
   "Multifamily Housing - Primary Hot Water Fuel Type for units",
   "Duct Pressure Test Leakage Percentage",
   "Retail Store - Number of Walk-in Refrigeration/Freezer Units",
   "Financial Office - Number of Workers on Main Shift",
   "Contact Address 1",
   "Contact Address 2",
   "Senior Care Community - Number of Commercial Refrigeration/ Freezer Units",
   "Design Swimming Pool - Gross Floor Area",
   "Water Alerts",
   "Annual Efficiency Unit",
   "Barracks - Dining Hall",
   "Zoo - Computer Density",
   "Hotel - Full Service Spa Floor Area",
   "Electric Distribution Utility",
   "Design Total GHG Emissions Intensity",
   "Prison/Incarceration - Computer Density",
   "Window Height",
   "Guiding Principles - Checklist Manager",
   "Measure Capital Replacement Costs",
   "Rate Structure End Date",
   "Thermal Efficiency",
   "Replaced/modified/removed system identifier",
   "Schedule Type",
   "District Chilled Water",
   "Minimum Outside Air Percentage",
   "Lifestyle Center - Computer Density",
   "Typical Exterior Wall Type",
   "Design Other - Lodging/Residential - Gross Floor Area",
   "Laundry Type",
   "Pre-school/Daycare - Number of Computers",
   "Compressor Unloader Stages",
   "Design Source Energy Use",
   "Wall Insulation Continuity",
   "Financial Office - Number of Computers",
   "GHG Emissions",
   "Wholesale Club/Supercenter- Open or Closed Refrigeration Density",
   "Source EUI",
   "Property Management Company",
   "Municipally Supplied Reclaimed Water: Combined Indoor/Outdoor or Other Use",
   "Other - Specialty Hospital - Gross Floor Area",
   "Bowling Alley - Gross Floor Area",
   "Wholesale Club/Supercenter- Computer Density",
   "K-12 School - Number of Computers",
   "K-12 School - Gymnasium Floor Area",
   "Heat Pump Backup Heating Switchover Temperature",
   "Stadium - Gross Floor Area",
   "Water/Wastewater Biomass GHG Emissions Intensity",
   "Fenestration R-value",
   "Return Duct Percent Conditioned Space",
   "Indoor Arena - Size of Electronic Scoreboards",
   "Barracks - Computer Lab",
   "Fuel Oil Cost",
   "Wastewater Treatment Plant - Average Effluent Biological Oxygen Demand",
   "Ground Coupling",
   "Diesel",
   "Other - Education - Gross Floor Area",
   "Design Other - Mall - Gross Floor Area",
   "Other - Weekly Operating Hours",
   "Demand Ratchet Percentage",
   "Premises Gross Floor Area",
   "Scope",
   "Design District Steam Use",
   "Retail Store - Weekly Operating Hours",
   "Other - Education - Number of Workers on Main Shift",
   "Automobile Dealership - Gross Floor Area",
   "Water Current Date",
   "Design Temperature Difference",
   "Number of Months in Operation",
   "Barracks- Gross Floor Area",
   "Fast Food Restaurant - Weekly Operating Hours",
   "Locations of exterior water intrusion damage",
   "Boiler Insulation R Value",
   "Hospital - Percent That Can Be Cooled",
   "Pump Application",
   "Design Bank Branch - Gross Floor Area",
   "Enclosed Mall - Computer Density",
   "Hotel - Room Density",
   "IT System Type",
   "Convenience Store without Gas Station - Weekly Operating Hours",
   "Guiding Principle 1.1 Integrated - Team",
   "Wall Area",
   "Certification Year",
   "Roller Rink - Weekly Operating Hours",
   "Non-Refrigerated Warehouse - Gross Floor Area",
   "Motor Enclosure Type",
   "Target Finder Baseline",
   "Design Target % Better Than Median Source EUI",
   "Net Present Value",
   "District Hot Water Cost",
   "Home Energy Score",
   "ENERGY STAR Application Status",
   "Estimated Savings from Energy Projects, Cumulative",
   "Other - Specialty Hospital - Computer Density",
   "Non-Refrigerated Warehouse - Walk-in Refrigeration Density",
   "Swimming Pool - Months in Use",
   "Skylight Solar tube",
   "Avoided Emissions - Offsite Green Power",
   "Police Station - Computer Density",
   "Space Peak Number of Occupants",
   "Outpatient Rehabilitation/Physical Therapy - Worker Density",
   "Design Repair Services - Gross Floor Area",
   "Courthouse - Gross Floor Area",
   "Capacity",
   "Pump Maximum Flow Rate",
   "Design Museum - Gross Floor Area",
   "Other - Stadium - Number of Sporting Events per Year",
   "Economizer Control",
   "Water/Wastewater Investment in Energy Projects, Cumulative",
   "Design Other - Recreation - Gross Floor Area",
   "Anti-Sweat Heaters",
   "Coal Cost",
   "Window Frame Type",
   "Other - Education - Worker Density",
   "Measure Implementation Status",
   "Single Family Home - Bedroom Density",
   "Certification Expiration Date",
   "Design Mailing Center/Post Office - Gross Floor Area",
   "Roof Color",
   "Windows Gas Filled",
   "Design Kerosene Use",
   "SHW Control Type",
   "Other Use",
   "Distribution Center - Walk-in Refrigeration Density",
   "Annual Savings Cost",
   "PV System Location",
   "Municipally Supplied Potable Water - Indoor Cost",
   "Municipally Supplied Reclaimed Water - Indoor Use",
   "Most Recent Sale Date",
   "Design College/University - Gross Floor Area",
   "Indoor Arena - Computer Density",
   "Vocational School - Number of Computers",
   "Average Weekly Business Hours",
   "Supermarket/Grocery - Computer Density",
   "Weather Normalized Water/Wastewater Source EUI",
   "Lifestyle Center - Weekly Operating Hours",
   "Reheat Control Strategy",
   "Urgent Care/Clinic/Other Outpatient - Computer Density",
   "Schedule Begin Month",
   "Other - Services - Number of Workers on Main Shift",
   "Country",
   "Primary Service Hot Water Fuel",
   "Plug Load Type",
   "Number of Occupants",
   "Vocational School - Number of Workers on Main Shift",
   "Data Center - UPS Output Site Energy",
   "Green Power - Onsite and Offsite",
   "Guiding Principle 5.3 Materials - Environmentally Preferred Products",
   "Clothes Washer Capacity",
   "Roller Rink - Worker Density",
   "Data Center - Cooling Equipment Redundancy",
   "Vestibule",
   "Auditor Company",
   "Building air leakage",
   "Guiding Principles - Principles Date Anticipated",
   "Urgent Care/Clinic/Other Outpatient - Gross Floor Area",
   "Typical Window Frame",
   "Roller Rink - Gross Floor Area",
   "Zoo - Number of Workers on Main Shift",
   "Percent Better than National Median Water/Wastewater Source EUI",
   "Daylighting Control Steps",
   "ASHRAE Baseline Lighting Power Density",
   "First Cost",
   "Casino - Gross Floor Area",
   "Other - Stadium - Number of Walk-in Refrigeration/Freezer Units",
   "Laundry Equipment Usage",
   "Retail Store - Cash Register Density",
   "Guiding Principle 3.4 Water - Efficient Products",
   "Source EUI - Adjusted to Current Year",
   "Barracks- Percent That Can Be Cooled",
   "Source Site Ratio",
   "ENERGY STAR Certification - Next Eligible Date",
   "Coal - Bituminous Use",
   "Water Cooled Condenser Flow Control",
   "Design Pre-school/Daycare - Gross Floor Area",
   "Repair Services - Number of Workers on Main Shift",
   "Guiding Principle 4.4 Indoor Environment - Daylighting and Occupant Controls Any Option",
   "Property Floor Area",
   "Control Technology",
   "Installed Fan Flow Rate",
   "Contact Postal Code",
   "Fuel Oil #2 Use",
   "Percent Better Than Baseline Design Site Energy Use Intensity",
   "Typical Floor R-Value",
   "Bowling Alley - Number of Workers on Main Shift",
   "Wall Framing Factor",
   "HPWH Minimum Air Temperature",
   "Other - Public Services - Computer Density",
   "Veterinary Office - Gross Floor Area",
   "Solar Thermal System Type",
   "M&V Option",
   "Primary Heating Fuel Type",
   "Refrigerant Subcooler",
   "Design Senior Care Community - Gross Floor Area",
   "Pre-school/Daycare - Number of Workers on Main Shift",
   "Solar Thermal System Storage Volume",
   "Wall Framing Material",
   "Race Track - Gross Floor Area",
   "Boiler Entering Water Temperature",
   "Refrigeration Unit is ENERGY STAR Rated",
   "Pool Surface Area",
   "Automobile Dealership - Number of Computers",
   "Utility Billpayer",
   "Auditor Qualification State",
   "District Steam Cost",
   "Percent of Electricity that is Green Power",
   "Dishwasher Hot Water Use",
   "Library - Number of Workers on Main Shift",
   "Fuel Generated",
   "Supermarket/Grocery - Gross Floor Area",
   "Design Hospital - Gross Floor Area",
   "Energy/Power Station - Weekly Operating Hours",
   "Outside Air Reset Maximum Heating Supply Temperature",
   "Floor Insulation Thickness",
   "Avoided Emissions - Onsite and Offsite Green Power",
   "Hospital - Percent That Can Be Heated",
   "Federal Agency",
   "Tank Height",
   "Heated Floor Area",
   "Floor Area Source",
   "Stadium - Percent That Can Be Cooled",
   "Social/Meeting Hall - Gross Floor Area",
   "Performing Arts - Computer Density",
   "Stadium - Gross Floor Area",
   "Worship Facility - Seating Capacity",
   "Energy Baseline Date",
   "Primary Property Type - EPA Calculated",
   "Weather Normalized Source Energy Use",
   "Personal Services - Worker Density",
   "Self-Storage Facility - Number of Computers",
   "Hospital - Maximum Number of Floors",
   "Museum - Weekly Operating Hours",
   "Stadium - Size of Electronic Scoreboards",
   "Design Electricity Use - Generated from Onsite Renewable Systems and Used Onsite",
   "Annual Savings Source Energy",
   "Design Target Total GHG Emissions",
   "Recirculation Control Type",
   "Design Other - Restaurant/Bar - Gross Floor Area",
   "Quantity",
   "Guiding Principle 4.6 Indoor Environment - Integrated Pest Management",
   "Hospital - Laboratory",
   "Resource Generated On Site",
   "Other - Utility - Weekly Operating Hours",
   "Biomass GHG Emissions Intensity",
   "Weather Station Name",
   "Guiding Principles - % In Process",
   "Retail Store - Gross Floor Area",
   "Worship Facility - Weekly Operating Hours",
   "Refrigerant Charge Factor",
   "Solar Thermal System Collector Area",
   "Aspect Ratio",
   "Other - Services - Worker Density",
   "Year of Last Energy Audit",
   "Indoor Arena - Number of Computers",
   "Parking - Gross Floor Area",
   "Cooling Type",
   "Daylight Sensors",
   "Interior Visible Absorptance",
   "Crankcase Heater",
   "Floor Covering",
   "Simple Payback",
   "Year of Last Major Remodel",
   "Metering Configuration",
   "Refrigerated Warehouse - Number of Workers on Main Shift",
   "Refrigeration Unit Size",
   "IT Energy Intensity",
   "Refrigeration Unit is Third Party Certified",
   "Economizer",
   "Wholesale Club/Supercenter- Number of Walk-in Refrigeration/Freezer Units",
   "Auditor Team Member with Certification",
   "K-12 School - Percent That Can Be Cooled",
   "Social/Meeting Hall - Number of Workers on Main Shift",
   "Site Address Line 2",
   "Backup Generator",
   "Roller Rink - Number of Computers",
   "Site Address Line 1",
   "Design Library - Gross Floor Area",
   "IT Standby Power",
   "Fire Station - Weekly Operating Hours",
   "Premises Postal Code",
   "Conveyance System Type",
   "Race Track - Computer Density",
   "Design Site EUI",
   "Roof Type",
   "Convenience Store with Gas Station - Weekly Operating Hours",
   "Design Target Total GHG Emissions Intensity",
   "K-12 School - Cooking Facilities",
   "K-12 School - Worker Density",
   "Retail Store - Single Store",
   "Design Site EUI",
   "IT Peak Power",
   "Metered Areas",
   "Recirculation Energy Loss Rate",
   "Lighting is FEMP Designated Product",
   "Design Fire Station - Gross Floor Area",
   "Distribution Type",
   "Design Roller Rink - Gross Floor Area",
   "Solar Heat Gain Coefficient SHGC",
   "Multifamily Housing - Number of Residential Living Units",
   "Hotel - Amount of Laundry Processed On-site Annually",
   "Doors Weather-Stripped",
   "Restaurant - Number of Computers",
   "Bar/Nightclub - Worker Density",
   "Electric Demand Rate",
   "Food Service - Weekly Operating Hours",
   "Design Prison/Incarceration - Gross Floor Area",
   "Heat Recovery Efficiency",
   "Guiding Principle 2.1 Energy Efficiency - Option 3",
   "Guiding Principle 2.1 Energy Efficiency - Option 2",
   "Guiding Principle 2.1 Energy Efficiency - Option 1",
   "Cooling Equipment Redundancy",
   "Space Floors Below Grade",
   "Design Coal - Bituminous Use",
   "Split Condenser",
   "Wood Use",
   "Other Water Sources - Indoor Intensity",
   "Dishwasher Type",
   "Movie Theater - Worker Density",
   "Light Shelf Exterior Protrusion",
   "Primary Air Distribution Type",
   "Design Bowling Alley - Gross Floor Area",
   "Boiler percent condensate return",
   "Fire Station - Worker Density",
   "Food Sales - Weekly Operating Hours",
   "Mailing Center/Post Office - Number of Computers",
   "Automobile Dealership - Computer Density",
   "Horizontal Abutments",
   "Space Use Description",
   "Fan Flow Control Type",
   "Design Indoor Arena - Gross Floor Area",
   "Retail Store - Number of Workers on Main Shift",
   "On-Site Generation Type",
   "Fast Food Restaurant - Number of Computers",
   "Minimum Dimming Power Fraction",
   "Target Energy Cost",
   "National Average EUI",
   "Owner Street Address",
   "Other - Mall - Gross Floor Area",
   "Air Duct Configuration",
   "Mailing Center/Post Office - Gross Floor Area",
   "Water/Wastewater Indirect GHG Emissions Intensity",
   "Year Of Latest Retrofit",
   "PV System Inverter Efficiency",
   "Hospital - Full Time Equivalent Workers",
   "Supermarket/Grocery - Walk-in Refrigeration Density",
   "Design Food Service - Gross Floor Area",
   "Total Water Cost",
   "Clothes Washer Loader Type",
   "Water Fixture Volume per Cycle",
   "Water Fixture Cycles per day",
   "Stadium - Computer Density",
   "Senior Care Community - Computer Density",
   "Social/Meeting Hall - Weekly Operating Hours",
   "Office - Computer Density",
   "Maximum Fan Power",
   "Typical Skylight Area",
   "Visible Transmittance",
   "Number of Cooling Stages",
   "Veterinary Office - Worker Density",
   "Wastewater Treatment Plant - Plant Design Flow Rate",
   "Office - Weekly Operating Hours",
   "Self-Storage Facility - Gross Floor Area",
   "Residual Value",
   "Power Plant",
   "Liquid Propane Use",
   "Window Glass Layers",
   "Design Other - Utility - Gross Floor Area",
   "Minimum Fan Flow Rate",
   "Stadium - Percent That Can Be Heated",
   "Stadium - Number of Sporting Events per Year",
   "Minimum Fan Speed as a Fraction of Maximum - Cooling",
   "Fan Efficiency",
   "Design Other - Public Services - Gross Floor Area",
   "Wastewater Treatment Plant - Average Influent Biological Oxygen Demand",
   "Enclosed Mall - Number of Workers on Main Shift",
   "Energy/Power Station - Number of Computers",
   "Stadium - Walk-in Refrigeration Density",
   "SHW Setpoint Temp",
   "Duty Cycle",
   "Wall Insulation Type",
   "College/University - Computer Density",
   "Design Race Track - Gross Floor Area",
   "Retail Store - Worker Density",
   "Natural Gas Use",
   "Energy Storage Type",
   "Food Sales - Worker Density",
   "Solar Thermal System Collector Azimuth",
   "Ambulatory Surgical Center - Gross Floor Area",
   "Manufacturing/Industrial Plant - Number of Workers on Main Shift",
   "Occupancy Sensors",
   "Calculation Method",
   "Wholesale Club/Supercenter- Percent That Can Be Cooled",
   "Design Aquarium - Gross Floor Area",
   "Social/Meeting Hall - Number of Computers",
   "Wastewater Treatment Plant - Fixed Film Trickle Filtration Process",
   "Design Courthouse - Gross Floor Area",
   "Energy/Power Station - Worker Density",
   "Design Target Water/Wastewater Source EUI",
   "Overhang Projection",
   "National Median ENERGY STAR Score",
   "Strip Mall - Computer Density",
   "Barracks - Room Density",
   "Plug Load Equipment is ENERGY STAR Rated",
   "Occupancy",
   "Enclosed Mall - Worker Density",
   "Fitness Center/Health Club/Gym - Gross Floor Area",
   "Light Shelf Interior Protrusion",
   "Hotel- Number of Commercial Refrigeration/Freezer Units",
   "Required Ventilation Rate",
   "Guiding Principle 5.4 Materials - Waste and Materials Mgmt",
   "Mailing Center/Post Office - Computer Density",
   "Guiding Principle 3.3 Water - Stormwater",
   "Design Laboratory - Gross Floor Area",
   "Bank Branch - Number of Workers on Main Shift",
   "Medical Office - Number of MRI Machines",
   "Laboratory - Computer Density",
   "Other - Stadium - Gross Floor Area",
   "Hospital - Tertiary Care",
   "Other - Public Services - Worker Density",
   "Wall R-Value",
   "Typical Window to Wall Ratio",
   "Refrigeration Energy",
   "Recommended Measure",
   "K-12 School - Number of Walk-in Refrigeration/Freezer Units",
   "Other - Stadium - Computer Density",
   "Design Wood Use",
   "Water Fixture Rated Flow Rate",
   "Number of Rooms",
   "Other Water Sources - Indoor Cost Intensity",
   "Door Glazed Area Fraction",
   "Recirculation",
   "Potable Water Savings",
   "Design Casino - Gross Floor Area",
   "Design Office - Gross Floor Area",
   "Typical Window Sill Height",
   "Floor Type",
   "Daylighting Illuminance Set Point",
   "Water-Side Economizer DB Temperature Maximum",
   "Strip Mall - Number of Computers",
   "Design Fast Food Restaurant - Gross Floor Area",
   "Other - Entertainment/Public Assembly - Gross Floor Area",
   "Anti-Sweat Heater Controls Manufacturer",
   "Design Wastewater Treatment Plant - Gross Floor Area",
   "Outpatient Rehabilitation/Physical Therapy - Number of Workers on Main Shift",
   "Other - Stadium - Walk-in Refrigeration Density",
   "Hospital - Number of Staffed Beds",
   "Design Retail Store - Gross Floor Area",
   "Design Worship Facility - Gross Floor Area",
   "Senior Care Community - Number of Commercial Washing Machines",
   "Burner Type",
   "Other - Services - Number of Computers",
   "Pump Minimum Flow Rate",
   "Movie Theater - Computer Density",
   "Bowling Alley - Computer Density",
   "Convenience Store with Gas Station - Gross Floor Area",
   "Multifamily Housing - Maximum Number of Floors",
   "National Median Water/Wastewater Site EUI",
   "Supermarket/Grocery - Number of Open or Closed Refrigeration/Freezer Units",
   "Guiding Principles - % Yes",
   "Refrigeration Unit Type",
   "Medical Office - MRI Machine Density",
   "Transformer Rated Power",
   "Rated Cooling Sensible Heat Ratio",
   "Domestic Hot Water Type",
   "Typical Window Area",
   "Laboratory - Worker Density",
   "Other Water Sources: Combined Indoor/Outdoor or Other Cost",
   "Barracks- Number of Rooms",
   "Alternate Baseline Lighting Power Density",
   "Office - Number of Workers on Main Shift",
   "Design Veterinary Office - Gross Floor Area",
   "Serves Multiple Buildings",
   "Performing Arts - Gross Floor Area",
   "Humidity Control Maximum",
   "Hospital - Onsite Laundry Facility",
   "Pool Pump Duty Cycle",
   "Process Load Installed Power",
   "Other - Public Services - Number of Computers",
   "Ownership Status",
   "Convenience Store with Gas Station - Number of Computers",
   "Zoo - Gross Floor Area",
   "Typical Window SHGC",
   "Outside Air Temperature Lower Limit Heating Reset Control",
   "National Median Reference Property Type",
   "Prison/Incarceration - Gross Floor Area",
   "Roof Area",
   "Convention Center - Number of Workers on Main Shift",
   "Pool is Heated",
   "Economizer Low Temperature Lockout",
   "ENERGY STAR Certification - Eligibility",
   "Design Performing Arts - Gross Floor Area",
   "Adult Education - Computer Density",
   "Worship Facility - Open All Weekdays",
   "Indoor Arena - Number of Sporting Events per Year",
   "Scenario Name",
   "Performing Arts - Number of Computers",
   "Generation Annual Operation Hours",
   "Total GHG Emissions Intensity",
   "Reactive Power Charge",
   "Technology Category",
   "Roof Exterior Thermal Absorptance",
   "Other - Mall - Number of Computers",
   "Interior Automated Shades",
   "Design Ice/Curling Rink - Gross Floor Area",
   "College/University - Enrollment",
   "Roof Framing Depth",
   "Evaporative Cooling Entering Supply Air DB Temperature",
   "Annual Fuel Use Consistent Units",
   "Design Target Site EUI",
   "Pool Water Temperature",
   "Condensing Temperature",
   "Bank Branch - Gross Floor Area",
   "Other - Technology/Science - Weekly Operating Hours",
   "Data Center - National Median PUE",
   "Cooling Stage Capacity",
   "District Chilled Water Use",
   "Outdoor Water Cost",
   "Aquarium - Number of Computers",
   "K-12 School - High School",
   "Other - Utility - Worker Density",
   "Food Service - Worker Density",
   "Laundry Unit Quantity",
   "Pool Type",
   "Fuel Oil Cost",
   "Multifamily Housing - Percent of Gross Floor Area That is Common Space Only",
   "Design Adult Education - Gross Floor Area",
   "Police Station - Weekly Operating Hours",
   "Electricity Cost",
   "Light Shelf Distance from Top",
   "Laundry Unit Year of Manufacture",
   "Weather Data Source",
   "Roof Exterior Solar Absorptance",
   "Supermarket/Grocery - Percent That Can Be Cooled",
   "Design PUE",
   "Food Service - Computer Density",
   "Fitness Center/Health Club/Gym - Weekly Operating Hours",
   "Residence Hall/ Dormitory - Dining Hall",
   "Duct Pressure Test Leakage cfm",
   "Data Center - IT Site Energy",
   "Laboratory - Weekly Operating Hours",
   "Estimated Savings from Energy Projects, Cumulative",
   "Roof Framing Material",
   "Lifestyle Center - Number of Workers on Main Shift",
   "Roof Insulated Area",
   "CMU Fill",
   "Evaporator Pressure Regulators",
   "Cooling is FEMP Designated Product",
   "Emissions Factor - Source",
   "Other - Stadium - Size of Electronic Scoreboards",
   "Indoor Arena - Number of Concert/Show Events per Year",
   "Retail Store - Walk-in Refrigeration Density",
   "Window Horizontal Spacing",
   "Winter Peak",
   "Roof R-Value",
   "Other - Lodging/Residential - Number of Workers on Main Shift",
   "Hotel - Gross Floor Area",
   "Residence Hall/Dormitory - Gross Floor Area",
   "Other - Restaurant/Bar - Gross Floor Area",
   "Municipally Supplied Reclaimed Water - Indoor Cost",
   "Economizer Enthalpy Control Point",
   "Personal Services - Number of Workers on Main Shift",
   "Data Center - Gross Floor Area",
   "College/University - Grant Dollars",
   "Outpatient Rehabilitation/Physical Therapy - Weekly Operating Hours",
   "Wholesale Club/Supercenter- Cash Register Density",
   "Self-Storage Facility - Worker Density",
   "Condensing Operation",
   "Museum - Worker Density",
   "Fan Placement",
   "Lamp Length",
   "Data Center - IT Energy Configuration",
   "Medical Office - Surgical Operating Bed Density",
   "Typical Skylight U-Value",
   "Potable",
   "Quality Alert-Space Alert",
   "Stadium - Percent That Can Be Heated",
   "Percent of RECs Retained",
   "Wholesale Club/Supercenter- Number of Workers on Main Shift",
   "National Median Site Energy Use",
   "Lighting Type",
   "Anti-Sweat Heater Controls",
   "REALPac Energy Benchmarking Program Building Name",
   "Manufacturing/Industrial Plant - Worker Density",
   "Stadium - Number of Special/Other Events per Year",
   "Non-Refrigerated Warehouse - Weekly Operating Hours",
   "Design Target Site Energy Use",
   "Movie Theater - Gross Floor Area",
   "Museum - Number of Computers",
   "Other - Technology/Science - Computer Density",
   "Personal Services - Number of Computers",
   "Primary Contact",
   "Other - Mall - Weekly Operating Hours",
   "Other - Restaurant/Bar - Worker Density",
   "Food Sales - Number of Computers",
   "Installed Power",
   "Primary Service Hot Water Location",
   "Rated Lamp Life",
   "Natural Gas Use",
   "Clothes Washer Water Factor",
   "Energy Cost",
   "Cooling Tower Control Type",
   "Annual Water Cost Savings",
   "Ice/Curling Rink - Gross Floor Area",
   "Design Water/Wastewater Site EUI",
   "Movie Theater - Number of Computers",
   "Plumbing Penetration Sealing",
   "Weather Normalized Site EUI",
   "Personal Services - Weekly Operating Hours",
   "Other - Lodging/Residential - Weekly Operating Hours",
   "Cooling Degree Days",
   "Enclosed Mall - Gross Floor Area",
   "Duct Surface Area",
   "Self-Storage Facility - Weekly Operating Hours",
   "Owner Email Address",
   "Pump Installed Flow Rate",
   "Hospital - Licensed Bed Capacity Density",
   "Climate Zone",
   "Police Station - Gross Floor Area",
   "Other - Entertainment/Public Assembly - Computer Density",
   "Other - Technology/Science - Worker Density",
   "Senior Care Community - Number of Computers",
   "Distance Between Vertical Fins",
   "ENERGY STAR Certification - Profile Published",
   "Senior Care Community - Percent That Can Be Cooled",
   "Input Voltage",
   "Electricity Sourced from Onsite Renewable Systems",
   "Motor RPM",
   "Ownership",
   "Desuperheat Valve",
   "Coke Cost",
   "Fan Size",
   "Pool Hours Uncovered",
   "Water-Side Economizer Temperature Maximum",
   "Veterinary Office - Number of Computers",
   "Heating Degree Days",
   "Portfolio Manager Parent Property ID",
   "Senior Care Community - Number of Workers on Main Shift",
   "Type of resource meter",
   "Museum - Number of Workers on Main Shift",
   "Wall Exterior Thermal Absorptance",
   "Aquarium - Worker Density",
   "Percent Skylight Area",
   "Non-Refrigerated Warehouse - Worker Density",
   "Other Financial Incentives",
   "Target Site Energy Use",
   "College/University - Number of Workers on Main Shift",
   "Guiding Principle 3.2 Outdoor Water - Option 3",
   "Guiding Principle 3.2 Outdoor Water - Option 2",
   "Guiding Principle 3.2 Outdoor Water - Option 1",
   "Water-Side Economizer Temperature Setpoint",
   "Pump Operation",
   "Other - Specialty Hospital - Worker Density",
   "Target Total GHG Emissions",
   "Distribution Center - Percent That Can Be Heated",
   "Heat Recovery Type",
   "Drinking Water Treatment & Distribution - Gross Floor Area",
   "Quality Alert-Energy Alerts",
   "Urgent Care/Clinic/Other Outpatient - Number of Workers on Main Shift",
   "Refrigeration Compressor Type",
   "Floor Area Value",
   "Work Plane Height",
   "Floor Construction Type",
   "Avoided Emissions - Onsite Green Power",
   "Benchmark Type",
   "Multifamily Housing - Number of Dishwasher Hookups",
   "Roof Slope",
   "Multifamily Housing - Percent That Can Be Cooled",
   "Annual Combined Whole Building Annual Weather Normalized Source Resource Use",
   "Primary Heating Type",
   "Data Center - PUE",
   "Ambulatory Surgical Center - Number of Workers on Main Shift",
   "Roller Rink - Computer Density",
   "Race Track - Weekly Operating Hours",
   "Primary Fan Configuration",
   "ENERGY STAR Certification - Last Approval Date",
   "Avoided Emissions",
   "Generation Capacity Unit",
   "Other - Restaurant/Bar - Computer Density",
   "Design Single Family Home - Gross Floor Area",
   "Fuel Oil Cost",
   "Marginal Sell Rate",
   "Pool Control Type",
   "Name of Audit Certification Holder",
   "Roof Framing Configuration",
   "Floors Partially Below Grade",
   "Guiding Principle 4.5 Indoor Environment - Low-Emitting Materials",
   "Service and Product Provider",
   "Fast Food Restaurant - Computer Density",
   "Heating Delivery Type",
   "Measure Name",
   "Normalization Start Year",
   "Bar/Nightclub - Number of Computers",
   "Senior Care Community - Residential Washing Machine Density",
   "Laboratory - Number of Computers",
   "Design Direct GHG Emissions",
   "Number of Heating Stages",
   "Arch2030 Baseline",
   "Fenestration Type",
   "Vertical Edge Fin Only",
   "Owner Postal Code",
   "Municipally Supplied Potable Water - Outdoor Cost",
   "Year PM Benchmarked",
   "Design Biomass GHG Emissions",
   "Cooling is ENERGY STAR Rated",
   "Wall Insulation Thickness",
   "Other - Specialty Hospital - Number of Workers on Main Shift",
   "Design Convention Center - Gross Floor Area",
   "Courthouse - Worker Density",
   "Residence Hall/Dormitory - Percent That Can Be Heated",
   "Zoo - Number of Computers",
   "Ambulatory Surgical Center - Number of Computers",
   "Other - Utility - Computer Density",
   "Prison/Incarceration - Number of Computers",
   "Design Data Center - Gross Floor Area",
   "Guiding Principle 5.2 Materials - Biobased Content",
   "Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems",
   "Water Use",
   "Other - Lodging/Residential - Number of Computers",
   "Bowling Alley - Number of Computers",
   "Indoor Water Cost Intensity",
   "Supermarket/Grocery - Number of Cash Registers",
   "eGRID Region Code",
   "Guiding Principle 5.1 Materials - Recycled Content",
   "Year Occupied",
   "Financial Office - Computer Density",
   "Typical Window U-Value",
   "Wholesale Club/Supercenter- Walk-in Refrigeration Density",
   "Heating Refrigerant Type",
   "Outside Air Temperature Upper Limit Heating Reset Control",
   "Distribution Center - Number of Workers on Main Shift",
   "Automobile Dealership - Number of Workers on Main Shift",
   "Funding from Rebates",
   "Process Load Type",
   "Design Propane Use",
   "Building air leakage unit",
   "Average Cooling Operating Hours",
   "Stadium - Number of Computers",
   "Supermarket/Grocery - Number of Computers",
   "Social/Meeting Hall - Computer Density",
   "Premises Tax Map Number",
   "Retro-commissioning Date",
   "Water/Wastewater Estimated Savings from Energy Projects, Cumulative",
   "Case Door Orientation",
   "Senior Care Community - Number of Residential Washing Machines",
   "Office - Percent That Can Be Heated",
   "Movie Theater - Weekly Operating Hours",
   "Urgent Care/Clinic/Other Outpatient - Number of Computers",
   "U.S. Federal Campus",
   "Tightness",
   "K-12 School - Student Seating Capacity",
   "National Median Total GHG Emissions",
   "Multiple Building Heights",
   "Hotel - Percent That Can Be Heated",
   "Annual Combined Whole Builidng Annual Site Energy Use Intensity",
   "Other - Services - Gross Floor Area",
   "Prison/Incarceration - Number of Workers on Main Shift",
   "Bank Branch - Computer Density",
   "Other - Stadium - Number of Concert/Show Events per Year",
   "Number of Computers",
   "Scenario Type",
   "Floor Framing Depth",
   "Reference Case",
   "Wastewater Treatment Plant - Nutrient Removal",
   "Municipally Supplied Potable Water - Indoor Intensity",
   "Condenser Fan Speed Operation",
   "Weather Normalized Water/Wastewater Site Natural Gas Intensity",
   "Pre-school/Daycare - Worker Density",
   "Plug Load Standby Power",
   "Strip Mall - Weekly Operating Hours",
   "Indoor Arena - Gross Floor Area",
   "Restaurant - Computer Density",
   "Multifamily Housing - Government Subsidized Housing",
   "Peak Occupancy Percentage",
   "Daily Hot Water Draw",
   "Analysis Period",
   "Fan Application",
   "Hotel - Percent That Can Be Cooled",
   "Premises Conditioned Floor Area",
   "Design Other - Gross Floor Area",
   "Onsite Renewable System Electricity Exported",
   "Pipe Insulation Thickness",
   "Site Use Description",
   "PV System Maximum Power Output",
   "Measure Scale of Application",
   "Transportation Terminal/Station - Number of Workers on Main Shift",
   "Residence Hall/Dormitory - Number of Rooms",
   "Storage Tank Insulation R-Value",
   "Single Family Home - Number of Bedrooms",
   "Non-Refrigerated Warehouse - Percent That Can Be Heated",
   "Ventilation Control Method",
   "Bank Branch - Percent That Can Be Heated",
   "Medical Office - Percent That Can Be Heated",
   "Bank Branch - Worker Density",
   "Supermarket/Grocery - Cooking Facilities",
   "Hospital - Gross Floor Area",
   "Guiding Principle 3.1 Water - Indoor Water Any Option",
   "Typical Ground Coupling Type",
   "Utility Name",
   "Design Stadium - Gross Floor Area",
   "Other - Entertainment/Public Assembly - Worker Density",
   "Tightness/Fit Condition",
   "Design Other - Services - Gross Floor Area",
   "Design Ambient Temperature",
   "College/University - Number of Computers",
   "Retail Store - Number of Computers",
   "Pre-school/Daycare - Computer Density",
   "Wall Insulation Material",
   "Gas Price Escalation Rate",
   "Absorption Stages",
   "Floor R-Value",
   "Floor Area Custom Name",
   "Water/Wastewater Direct GHG Emissions Intensity",
   "Multifamily Housing - Percent That Can Be Heated",
   "Retail Store - Computer Density",
   "Retail Store - Number of Open or Closed Refrigeration/Freezer Units",
   "Stadium - Number of Walk-in Refrigeration/Freezer Units",
   "Stadium - Walk-in Refrigeration Density",
   "Occupant Activity Level",
   "Pre-school/Daycare - Gross Floor Area",
   "Wall Framing Configuration",
   "Cooking Capacity Unit",
   "Hotel - Commercial Refrigeration Density",
   "K-12 School - Weekend Operation",
   "Fire Station - Number of Workers on Main Shift",
   "Data Center - PDU Input Site Energy",
   "Hospital - Full Time Equivalent Workers Density",
   "Premises Tax Book Number",
   "Supermarket/Grocery - Worker Density",
   "Certification Program",
   "Boiler Leaving Water Temperature",
   "Wholesale Club/Supercenter- Number of Computers",
   "Control Type",
   "Premises Block Number",
   "Hotel - Number of Workers on Main Shift",
   "Courthouse - Weekly Operating Hours",
   "Summer Peak",
   "Convention Center - Gross Floor Area",
   "Lamp Distribution Type",
   "Water-Side Economizer Type",
   "Manufacturing/Industrial Plant - Number of Computers",
   "Design Transportation Terminal/Station - Gross Floor Area",
   "PV System Array Azimuth",
   "Roof Insulation Type",
   "Premises Occupied Floor Area",
   "Skylight Operability",
   "Financial Office - Percent That Can Be Cooled",
   "SHW is ENERGY STAR Rated",
   "Stadium - Enclosed Floor Area",
   "Indirect GHG Emissions",
   "Guiding Principle 2.5 Energy - Benchmarking",
   "Lighting Control Type Occupancy",
   "Premises Custom ID",
   "Hospital - Number of Workers on Main Shift Density",
   "Design Fuel Oil #4 Use",
   "K-12 School - School District",
   "Municipally Supplied Reclaimed Water: Combined Indoor/Outdoor or Other Cost",
   "Wastewater Treatment Plant - Gross Floor Area",
   "Retail Store - Percent That Can Be Cooled",
   "End Time Stamp",
   "Design Lifestyle Center - Gross Floor Area",
   "Wholesale Club/Supercenter- Worker Density",
   "Design Other Use",
   "Source Energy Use - Adjusted to Current Year",
   "Annual Savings Site Energy",
   "Distribution Center - Worker Density",
   "Economizer Type",
   "Skylight Layout",
   "Senior Care Community - Resident Density",
   "Number of Units",
   "Automobile Dealership - Weekly Operating Hours",
   "Wastewater Treatment Plant - Average Influent Flow",
   "K-12 School - Gross Floor Area",
   "Swimming Pool - Location of Pool",
   "Manufacturing/Industrial Plant - Gross Floor Area",
   "College/University - Gross Floor Area",
   "Heating Staging",
   "Average Weekly Hours",
   "Total Heat Rejection",
   "Guiding Principles - % No",
   "Floor Framing Configuration",
   "Medical Office - Number of Surgical Operating Beds",
   "Restaurant - Worker Density",
   "Non-Refrigerated Warehouse - Number of Walk-in Refrigeration/Freezer Units",
   "Heating Setpoint setpoint",
   "Weather-Stripped",
   "Fuel Use Intensity",
   "Contact State",
   "Bowling Alley - Worker Density",
   "Bar/Nightclub - Gross Floor Area",
   "Locations of interior water intrusion damage",
   "Exterior Door Type",
   "Enclosed Mall - Number of Computers",
   "Slab Exposed Perimeter",
   "Type of Cooking Equipment",
   "Target Water/Wastewater Source EUI",
   "Stadium - Enclosed Floor Area",
   "Supermarket/Grocery - Weekly Operating Hours",
   "Stadium - Percent That Can Be Cooled",
   "Water/Wastewater Total GHG Emissions Intensity",
   "Discount Factor",
   "Retail Store - Percent That Can Be Heated",
   "Laboratory - Number of Workers on Main Shift",
   "Premises Count",
   "Urgent Care/Clinic/Other Outpatient - Weekly Operating Hours",
   "OM Cost Annual Savings",
   "Casino - Weekly Operating Hours",
   "Water Baseline Date",
   "Typical Window Type",
   "Steam Boiler Minimum Operating Pressure",
   "Energy Recovery Efficiency",
   "Duct Insulation R-Value",
   "Premises City",
   "Aquarium - Computer Density",
   "Strip Mall - Worker Density",
   "Annual Combined Whole Builidng Annual Source Energy Use Intensity",
   "Municipally Supplied Reclaimed Water - Outdoor Cost",
   "Indirect Tank Heating Source",
   "Other - Gross Floor Area",
   "Federal Department",
   "Other - Recreation - Number of Workers on Main Shift",
   "Single Family Home - Gross Floor Area",
   "Solar Thermal System Collector Tilt",
   "Fire Station - Gross Floor Area",
   "Typical Exterior Shading Type",
   "Guiding Principle 4.2 Indoor Environment - Moisture Control",
   "Ice/Curling Rink - Weekly Operating Hours",
   "Other Peak Rate",
   "Design Total GHG Emissions",
   "Hospital - MRI Density",
   "K-12 School - Computer Density",
   "Duct Insulation",
   "Electricity Use - Generated from Onsite Renewable Systems and Used Onsite",
   "Property Floor Area",
   "Resource",
   "PV Module Length",
   "Tank Perimeter",
   "Hospital - Licensed Bed Capacity",
   "Hot Water Boiler Maximum Flow Rate",
   "Ballast Type",
   "Indoor Arena - Number of Special/Other Events per Year",
   "Door Configuration",
   "Guiding Principle 1.5 Integrated - Commissioning",
   "Convention Center - Weekly Operating Hours",
   "Convention Center - Number of Computers",
   "Design Target Water/Wastewater Site EUI",
   "Case Return Line Diameter",
   "Radiant Barrier",
   "Bar/Nightclub - Number of Workers on Main Shift",
   "Parent Property Name",
   "Convenience Store with Gas Station - Number of Workers on Main Shift",
   "ENERGY STAR Certification - Application Status",
   "Veterinary Office - Number of Workers on Main Shift",
   "Conveyance Standby Power",
   "Outside Air Reset Maximum Cooling Supply Temperature",
   "Energy/Power Station - Computer Density",
   "Floor-to-Floor Height",
   "Stadium - Ice Events",
   "Transportation Terminal/Station - Weekly Operating Hours",
   "Primary Zonal Cooling Type",
   "eGRID Subregion",
   "Window Sill Height",
   "Food Sales - Number of Workers on Main Shift",
   "Convention Center - Worker Density",
   "Foundation Wall Insulation Condition",
   "Construction Status",
   "Indoor Arena - Walk-in Refrigeration Density",
   "Roof Insulation Condition",
   "Design Stadium - Gross Floor Area",
   "Indoor Arena - Enclosed Floor Area",
   "Electricity Use - Grid Purchase and Generated from Onsite Renewable Systems",
   "Heating Setback Frequency",
   "Barracks- Percent That Can Be Heated",
   "Self-Storage Facility - Computer Density",
   "Ice/Curling Rink - Worker Density",
   "Anti-Sweat Heater Controls Model Number",
   "Primary Zonal Cooling Fuel Type",
   "Foundation Wall Insulation Continuity",
   "Total GHG Emissions",
   "Municipally Supplied Reclaimed Water - Indoor Intensity",
   "Dishwasher Loads Per Week",
   "Other - Worker Density",
   "Food Sales - Computer Density",
   "Non-Potable Water used for Irrigation",
   "Asset Score",
   "Collection Date",
   "Electricity Use - Generated from Onsite Renewable Systems",
   "Other Water Sources - Outdoor Use",
   "Wall Framing Depth",
   "Natural Ventilation Rate",
   "Indoor Arena - Number of Walk-in Refrigeration/Freezer Units",
   "Design Target Source EUI",
   "Fire Station - Computer Density",
   "Refrigerated Warehouse - Gross Floor Area",
   "Foundation Wall Type",
   "Indoor Arena - Percent That Can Be Heated",
   "Input Capacity",
   "Natural Ventilation",
   "Design Greenhouse Gas Emissions Intensity",
   "Ambulatory Surgical Center - Weekly Operating Hours",
   "Other - Restaurant/Bar - Number of Computers",
   "Hot Water Boiler Minimum Flow Rate",
   "PV System Number of Modules per Array",
   "Propane Use",
   "Building Operator Name",
   "Primary Zonal Heating Type",
   "Lifestyle Center - Worker Density",
   "Owner Telephone Number",
   "Retail Store - Open or Closed Refrigeration Density",
   "Municipally Supplied Potable Water - Outdoor Use",
   "Heat Pump Backup AFUE",
   "Retail Store - Exterior Entrance to the Public",
   "Lifestyle Center - Gross Floor Area",
   "Food Service - Number of Computers",
   "Alternative Water Generated On-Site - Indoor Cost Intensity",
   "Bank Branch - Number of Computers",
   "Design Police Station - Gross Floor Area",
   "In Portfolio Manager",
   "Contact City",
   "Other - Utility - Number of Workers on Main Shift",
   "Primary Cooking Fuel",
   "PV System Number of Arrays",
   "Courthouse - Percent That Can Be Cooled",
   "Lighting Power Density",
   "Stadium - Size of Electronic Scoreboards",
   "Parking - Completely Enclosed Parking Garage Size",
   "Fixture Spacing",
   "Heating Stage Capacity",
   "Number of Exterior Doors",
   "Museum - Gross Floor Area",
   "Design Coke Use",
   "Design Personal Services - Gross Floor Area",
   "Lighting is ENERGY STAR Rated",
   "Green Power - Onsite",
   "Outside Air Temperature Lower Limit Cooling Reset Control",
   "Heating Setback Temperature",
   "Office - Worker Density",
   "Design Target ENERGY STAR Score",
   "Cooking Energy per Meal",
   "Ceiling Visible Absorptance",
   "Food Service - Number of Workers on Main Shift",
   "Third party certification",
   "Typical Window Visual Transmittance",
   "Stadium - Number of Special/Other Events per Year",
   "Motor Full Load Amps",
   "Number of Lamps per Luminaire",
   "Duct Sealing",
   "Design Parking - Gross Floor Area",
   "Other - Restaurant/Bar - Number of Workers on Main Shift",
   "Cooling Supply Air Temperature Control Type",
   "Supermarket/Grocery - Number of Workers on Main Shift",
   "Data Center - IT Source Energy",
   "Convenience Store without Gas Station - Computer Density",
   "Slab Insulation Thickness",
   "Design Energy Cost",
   "Pumping Configuration",
   "Federal Sustainability Checklist Completion Percentage",
   "Hospital - Number of Workers on Main Shift",
   "Strip Mall - Gross Floor Area",
   "Metered Areas",
   "Senior Care Community - Maximum Resident Capacity",
   "Other - Services - Weekly Operating Hours",
   "K-12 School - Percent That Can Be Heated",
   "Foundation Area",
   "Cooking Capacity",
   "Guiding Principles - Principles Date Achieved",
   "Design Movie Theater - Gross Floor Area",
   "Hotel - Cooking Facilities",
   "Design Urgent Care/Clinic/Other Outpatient - Gross Floor Area",
   "Single Family Home - Number of People",
   "Design Strip Mall - Gross Floor Area",
   "Source Energy Use",
   "District Steam",
   "Other Cost"])
